version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip
      - unzip terraform.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
  build:
    commands:
      - echo "Building infrastructure with Terraform"
      - terraform init
      - terraform apply -var-file=group2_cap2.tfvars --auto-approve
  post_build:
    commands:
      - echo "Build complete"
